apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgALIcIsS1FSeHHq2+5odMVC0FHWx6ONXfc7SZTUJXN82K3G1kzVMV1yVaEeir6M6BbALT7RLzU4pfKwC2tB3S5cAq4X8qTF18yuUSYrvTmK/4IIsLxiaFzxqTNQFbm5ckhTlkrgNfDXYrGM/brn4HWnQArjM1MwWUnmym15S0nPVgWiV8KTJwGRcaIrzXBT187hKx5GQOoGFZdijEMiShbDRHkGtcJ/bz0qffqTJhU9b9o1MWNYGzHg1U0ZLVNuRKqSTQVLgFNtZ8RGs83PtiXxhD+QFFq8VybcFDPu+zQ4c5lR7VxTUXHeaZBuoy71fyeDOk6oNXUczbyfppW5jIj2SOTXmJXhO3/KEN2g7Upt9PEfNbo+8HXg96g4DDPzKLhCDMnCdcs2RAU4+lFKr1/s+B8bdnujjaTU0qfjwj6x9SD0PriTnXU+Q31zcrO/FbX1Q35uqJ48tn5qcQlyCKiklIUqkuu/WYRpy734KayiQu9W3AQwFW5RfOw4d/zP1DNWd9crCpwWmDabnko3ncxIaJPDxSJP7n+nm1i+8cA0zUwX29bhILHI0fGXzOlzbpGx0yrubd8LR4ETVJTXgoObtJ1dVzp0WHDko6B/Gw5uQElme3bp24fhAHbh4vM2qp1jQ1YjGEEsBL5f1JXkWkElJYpavClxlqQ7/oaHs32gt4ZREmco0s7aywTIcnoPYZtMQMlPcDsDlYElwfGKBy+r9H/ykK1M5RoP
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

